### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by milesich** [aafeher/go-microdata-extract#2]
It panic when I am trying to extract data from `https://www.youtube.com/watch?v=phuiiNCxRMg`

```
panic: runtime error: index out of range [-1]

goroutine 131 [running]:
github.com/aafeher/go-microdata-extract/extractors.handleOpenGraphVideoProperty(0x4001b59500, {0x4002978c90?, 0xcafe70?, 0x1?}, {0x40029667b0?, 0xbce9fb?})
        /build/vendor/github.com/aafeher/go-microdata-extract/extractors/opengraph.go:377 +0x330
github.com/aafeher/go-microdata-extract/extractors.parseOpenGraphMetaTag(0x4001b59500, {0x400297e000, 0x13}, {0x40029667b0, 0x29})
        /build/vendor/github.com/aafeher/go-microdata-extract/extractors/opengraph.go:227 +0x1c90
github.com/aafeher/go-microdata-extract/extractors.extractOpenGraph({0x4002760000, 0x113090})
        /build/vendor/github.com/aafeher/go-microdata-extract/extractors/opengraph.go:181 +0x3e0
github.com/aafeher/go-microdata-extract/extractors.ParseXCards({0x4000119f00?, 0x4000c9a6e8?}, {0x4002760000, 0x113090})
        /build/vendor/github.com/aafeher/go-microdata-extract/extractors/xcards.go:88 +0x4c
github.com/aafeher/go-microdata-extract.(*Extractor).Extract.func2()
        /build/vendor/github.com/aafeher/go-microdata-extract/extract.go:147 +0x30
github.com/aafeher/go-microdata-extract.(*Extractor).Extract.func5({{0x9dbcff?, 0x8c374?}, 0x4000d978a0?})
        /build/vendor/github.com/aafeher/go-microdata-extract/extract.go:173 +0x78
created by github.com/aafeher/go-microdata-extract.(*Extractor).Extract in goroutine 123
        /build/vendor/github.com/aafeher/go-microdata-extract/extract.go:171 +0x724
```

**Comment by aafeher** [comment]
Thanks again @milesich!
Fixed in new release v0.1.4.
